# Generated by Django 4.0.1 on 2022-01-23 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.TimeField()),
                ('check_out_date', models.DateField()),
                ('check_out_time', models.TimeField()),
                ('date_booked', models.DateField()),
                ('is_cancelled', models.BooleanField()),
                ('cancelled_date', models.DateField(null=True)),
                ('total_days', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('no_of_rooms', models.IntegerField(default=1)),
                ('payment_ref', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
