# Generated by Django 4.0.1 on 2022-01-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_roombooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roombooking',
            name='message',
        ),
    ]
